name: Build and push CRMEB Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "11 20 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-latest-tag:
    name: Get latest tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CRMEB
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: crmeb/CRMEB
      - name: Get CRMEB latest tag
        id: tag
        run: echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0
      - name: Get my latest tag
        id: mytag
        run: echo "mytag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"
      - name: Add tag
        id: addtag
        if: steps.tag.outputs.tag != steps.mytag.outputs.mytag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag ${{ steps.tag.outputs.tag }}
          git push origin --tags
          echo "addtag=true" >> "$GITHUB_OUTPUT"

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      addtag: ${{ steps.addtag.outputs.addtag }}

  build-docker-image:
    needs: get-latest-tag
    if: needs.get-latest-tag.outputs.addtag == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout CRMEB
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: crmeb/CRMEB
          ref: '${{ needs.get-latest-tag.outputs.tag }}'
          path: CRMEB

      - name: CRMEB Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/varfly/CRMEB
          tags: |
            type=ref,event=tag
            type=raw,value=${{ needs.get-latest-tag.outputs.tag }}

      - name: nginx Docker meta
        id: meta-nginx
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/varfly/CRMEB-nginx
          tags: |
            type=ref,event=tag
            type=raw,value=${{ needs.get-latest-tag.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: varfly
          password: ${{ secrets.GH_PAT }}
          
      - name: Fix Dockerfile for PHP 7.4 packages
        run: |
          # 备份原始 Dockerfile
          cp ./CRMEB/docker-compose/php/Dockerfile ./CRMEB/docker-compose/php/Dockerfile.backup
          
          # 创建修复后的 Dockerfile
          cat > ./CRMEB/docker-compose/php/Dockerfile << 'EOF'
          FROM php:7.4-fpm AS crmeb_php
          WORKDIR "/var/www"

          # 安装系统依赖
          RUN apt-get update && apt-get install -y \
              libfreetype6-dev \
              libjpeg62-turbo-dev \
              libpng-dev \
              libzip-dev \
              libicu-dev \
              libxml2-dev \
              libxslt-dev \
              libcurl4-openssl-dev \
              libssl-dev \
              libonig-dev \
              libbz2-dev \
              libpq-dev \
              libgd-dev \
              && rm -rf /var/lib/apt/lists/*

          # 安装 PHP 扩展 - 只安装核心扩展
          RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
              && docker-php-ext-install -j$(nproc) \
                  bcmath \
                  gd \
                  mysqli \
                  zip \
                  intl \
                  xml \
                  curl \
                  mbstring \
                  pdo \
                  pdo_mysql

          # 安装 Redis 扩展
          RUN pecl install redis && docker-php-ext-enable redis

          # PHP 配置
          RUN echo "open_basedir = /tmp:/var" > /usr/local/etc/php/conf.d/open_basedir.ini

          # 添加我们的文件
          ADD ./crmeb /var/www
          ADD ./docker-compose/php/php-ini-overrides.ini /usr/local/etc/php/conf.d/99-overrides.ini
          EOF

      #- name: Get tag
      #  id: tag
      #  uses: devops-actions/action-get-tag@v1.0.1
      #  with:
      #    strip_v: true # Optional: Remove 'v' character from version

      - name: Build and push CRMEB Docker images to ghcr.io and DockerHub
        uses: docker/build-push-action@v6
        with:
          context: ./CRMEB
          file: ./CRMEB/docker-compose/php/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true

      - name: Build and push nginx Docker images to ghcr.io and DockerHub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}